# Generated by Django 5.2.17 on 2026-09-09 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=32)),
                (
                    "code_hash",
                    models.CharField(
                        help_text="Hash of the OTP code. The raw code is never stored.",
                        max_length=128,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("LOGIN", "Login")], default="LOGIN", max_length=32
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("attempts_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        help_text="Snapshot of the policy value at creation time."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OTP verification",
                "verbose_name_plural": "OTP verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "status"],
                        name="accounts_ot_phone_931fcd_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="accounts_ot_created_ca5b5b_idx"
                    ),
                ],
            },
        ),
    ]
