# Generated by Django 5.2.17 on 2026-09-09 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("APPLE", "Apple"), ("GOOGLE", "Google")],
                        max_length=16,
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(
                        help_text="Stable identifier at the provider (e.g. the OIDC 'sub' claim).",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email as reported by the provider; may differ from User.email.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "raw_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw provider payload, kept for debugging/audit.",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social account",
                "verbose_name_plural": "Social accounts",
                "ordering": ["-linked_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_user_id"],
                        name="accounts_so_provide_71a274_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="uniq_social_provider_identity",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="uniq_social_user_provider"
                    ),
                ],
            },
        ),
    ]
