# Generated by Django 5.2.17 on 2026-09-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_contractor",
            field=models.BooleanField(
                default=False,
                help_text="May also work as a contractor, in addition to their role.",
            ),
        ),
    ]
