# Generated by Django 5.2.17 on 2026-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_contractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="requested_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["requested_ip", "created_at"],
                name="accounts_ot_request_076a1d_idx",
            ),
        ),
    ]
