# Generated by Django 5.2.17 on 2026-09-24 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def sync_staff_with_role(apps, schema_editor):
    """
    الدور ADMIN وحده يمنح دخول اللوحة (راجع User.save). الصفوف القائمة
    تُصحَّح مرة واحدة: غير الأدمن يفقد is_staff/is_superuser.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="ADMIN").update(is_staff=True)
    User.objects.exclude(role="ADMIN").update(is_staff=False, is_superuser=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_security_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("ADMIN_LOGIN", "Admin login (second factor)"),
                ],
                default="LOGIN",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AdminLoginChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_login_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(sync_staff_with_role, migrations.RunPython.noop),
    ]
