# Generated by Django 5.2.17 on 2026-09-16 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_started_at_alter_job_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reported GPS accuracy radius in metres, if the device supplied it.",
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="When the device captured the fix (client clock — not trusted)."
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job location",
                "verbose_name_plural": "Job locations",
                "ordering": ["-received_at"],
            },
        ),
    ]
