# Generated by Django 5.2.17 on 2026-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_joblocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("ARRIVED", "Arrived"),
                    ("IN_PROGRESS", "In progress"),
                    (
                        "AWAITING_CUSTOMER_CONFIRMATION",
                        "Awaiting customer confirmation",
                    ),
                    ("COMPLETED", "Completed"),
                ],
                default="ASSIGNED",
                max_length=32,
            ),
        ),
    ]
