# Generated by Django 5.2.17 on 2026-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_arrived_at_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="auto_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="confirmation_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
