# Generated by Django 5.2.17 on 2026-09-16 17:20

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingconfig",
            name="active_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this configuration took effect.",
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="currency",
            field=models.CharField(
                default="AUD",
                help_text="ISO 4217 code; single-currency product for now.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="dispatch_offer_ttl_seconds",
            field=models.PositiveIntegerField(
                default=3600,
                help_text="How long a dispatch offer stays answerable.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="included_distance_km",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Free travel distance; only the excess is charged.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="maximum_travel_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("9999.99"),
                help_text="Cap on the travel component, however far the contractor is.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="pricing_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Incremented on every change; frozen onto offers and bookings.",
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="rounding_rule",
            field=models.CharField(
                choices=[
                    ("NEAREST_CENT", "Nearest cent"),
                    ("NEAREST_5C", "Nearest 5 cents"),
                    ("NEAREST_10C", "Nearest 10 cents"),
                    ("NEAREST_DOLLAR", "Nearest dollar"),
                ],
                default="NEAREST_CENT",
                help_text="Applied once, to the final total only.",
                max_length=16,
            ),
        ),
    ]
