# Generated by Django 5.2.17 on 2026-09-27 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_pricingconfig_active_from_pricingconfig_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingconfig",
            name="service_hours_enabled",
            field=models.BooleanField(
                default=False, help_text="Off: cleaners can be requested at any hour."
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="service_hours_end",
            field=models.TimeField(
                default=datetime.time(19, 0),
                help_text="Closing time, property-local and inclusive. May be earlier than the start (overnight).",
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="service_hours_start",
            field=models.TimeField(
                default=datetime.time(7, 0),
                help_text="Opening time, property-local. Used only when service hours are on.",
            ),
        ),
    ]
