# Generated by Django 5.2.17 on 2026-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_pricingconfig_service_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="reclean_guarantee",
            field=models.BooleanField(
                default=False,
                help_text="Customers can request a free re-clean within the guarantee window after completion.",
            ),
        ),
    ]
