# Generated by Django 5.2.17 on 2026-09-09 10:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("HOUSE", "House"),
                            ("UNIT", "Unit"),
                            ("TOWNHOUSE", "Townhouse"),
                            ("APARTMENT", "Apartment"),
                            ("OTHER", "Other"),
                        ],
                        default="HOUSE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("suburb", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NSW", "New South Wales"),
                            ("VIC", "Victoria"),
                            ("QLD", "Queensland"),
                            ("WA", "Western Australia"),
                            ("SA", "South Australia"),
                            ("TAS", "Tasmania"),
                            ("ACT", "Australian Capital Territory"),
                            ("NT", "Northern Territory"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postcode must be exactly 4 digits.",
                                regex="^\\d{4}$",
                            )
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(default="AU", editable=False, max_length=2),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("raw_input", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property address",
                "verbose_name_plural": "Property addresses",
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner", "is_active"], name="properties__owner_i_a56902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyaddress",
            index=models.Index(
                fields=["suburb", "state"], name="properties__suburb_1d8269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyaddress",
            index=models.Index(
                fields=["postcode"], name="properties__postcod_fd9a50_idx"
            ),
        ),
    ]
