# Generated by Django 5.2.17 on 2026-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_action_payload_payment_attempt_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
