# Generated by Django 5.2.17 on 2026-09-16 13:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0008_booking_public_reference_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BOOKING_ISSUE", "Booking issue"),
                            ("PAYMENT_ISSUE", "Payment issue"),
                            ("CONTRACTOR_ISSUE", "Contractor issue"),
                            ("APP_ISSUE", "App issue"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="SUBMITTED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — the booking this request is about.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_requests",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support request",
                "verbose_name_plural": "Support requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="support_sup_user_id_bcb34a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="support_sup_status_9a1ebd_idx"
                    ),
                    models.Index(
                        fields=["category"], name="support_sup_categor_fed5be_idx"
                    ),
                ],
            },
        ),
    ]
