# Generated by Django 5.2.17 on 2026-09-11 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("suburb", models.CharField(blank=True, max_length=120)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NSW", "New South Wales"),
                            ("VIC", "Victoria"),
                            ("QLD", "Queensland"),
                            ("WA", "Western Australia"),
                            ("SA", "South Australia"),
                            ("TAS", "Tasmania"),
                            ("ACT", "Australian Capital Territory"),
                            ("NT", "Northern Territory"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postcode must be exactly 4 digits.",
                                regex="^\\d{4}$",
                            )
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(default="AU", editable=False, max_length=2),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="UNAVAILABLE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor profile",
                "verbose_name_plural": "Contractor profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["availability_status"],
                        name="contractors_availab_305471_idx",
                    ),
                    models.Index(
                        fields=["suburb", "state"], name="contractors_suburb_1c8e09_idx"
                    ),
                ],
            },
        ),
    ]
