# Generated by Django 5.2.17 on 2026-09-11 21:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abn",
                    models.CharField(
                        help_text="11-digit ABN. Format validation only — not a registry lookup.",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ABN must be exactly 11 digits.",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_registrations",
                        to="contractors.contractorprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business registration",
                "verbose_name_plural": "Business registrations",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["contractor", "-created_at"],
                        name="contractors_contrac_0b3918_idx",
                    ),
                    models.Index(
                        fields=["status"], name="contractors_status_19d823_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_reference",
                    models.CharField(
                        help_text="Policy number or reference. Not a file upload (Infra §7).",
                        max_length=255,
                    ),
                ),
                ("expiry_date", models.DateField()),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_documents",
                        to="contractors.contractorprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance document",
                "verbose_name_plural": "Insurance documents",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["contractor", "-created_at"],
                        name="contractors_contrac_b45c5b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="contractors_status_a9f55a_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="contractors_expiry__93e272_idx"
                    ),
                ],
            },
        ),
    ]
