# Generated by Django 5.2.17 on 2026-09-16 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0002_businessregistration_insurancedocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorCurrentLocation",
            fields=[
                (
                    "contractor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="current_location",
                        serialize=False,
                        to="contractors.contractorprofile",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="Device capture time (client clock — not trusted)."
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contractor current location",
                "verbose_name_plural": "Contractor current locations",
            },
        ),
    ]
