# Generated by Django 5.2.17 on 2026-09-24 19:48

import apps.contractors.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0003_contractorcurrentlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessregistration",
            name="abn",
            field=models.CharField(
                help_text="11-digit ABN. Format and checksum validation only — not a registry lookup.",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ABN must be exactly 11 digits.", regex="^\\d{11}$"
                    ),
                    apps.contractors.models.validate_abn_checksum,
                ],
            ),
        ),
    ]
