# Generated by Django 5.2.17 on 2026-09-24 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(db_index=True, max_length=64)),
                (
                    "target_type",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log",
                "ordering": ["-created_at"],
            },
        ),
    ]
