# Generated by Django 5.2.17 on 2026-09-11 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("contractors", "0002_businessregistration_insurancedocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Distance used for this offer; frozen, never recomputed.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("offered_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_offers",
                        to="bookings.booking",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_offers",
                        to="contractors.contractorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch offer",
                "verbose_name_plural": "Dispatch offers",
                "ordering": ["-offered_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="bookings_di_status_1ef824_idx",
                    ),
                    models.Index(
                        fields=["booking", "status"],
                        name="bookings_di_booking_a61538_idx",
                    ),
                    models.Index(
                        fields=["contractor", "status"],
                        name="bookings_di_contrac_e0d474_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "contractor"),
                        name="unique_offer_per_booking_contractor",
                    )
                ],
            },
        ),
    ]
