# Generated by Django 5.2.17 on 2026-09-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_dispatchoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone derived from the property address; display only.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Visit date and time, stored in UTC.",
                null=True,
            ),
        ),
    ]
