# Generated by Django 5.2.17 on 2026-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_customer_timezone_booking_scheduled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="dispatch_status",
            field=models.CharField(
                choices=[
                    ("SEARCHING", "Searching"),
                    ("NO_CONTRACTOR", "No contractor available"),
                    ("ASSIGNED", "Assigned"),
                ],
                default="SEARCHING",
                help_text="Progress of the contractor search; display only.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="last_dispatch_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
