# Generated by Django 5.2.17 on 2026-09-16 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_dispatch_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="access_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Customer's own arrival instructions for this visit. Visible only to the assigned contractor.",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
    ]
