# Generated by Django 5.2.17 on 2026-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_access_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="public_reference",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Human-readable booking number (e.g. CLN-7F3K9Q); display only.",
                max_length=16,
                null=True,
            ),
        ),
    ]
