# Generated by Django 5.2.17 on 2026-09-16 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_public_reference_unique"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="currency",
            field=models.CharField(default="AUD", max_length=3),
        ),
        migrations.AddField(
            model_name="booking",
            name="max_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Customer-approved ceiling, frozen from the quote.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Opaque provider token for the selected method. Never card data.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pricing_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="requested_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="When the customer requested a cleaner (on-demand).",
            ),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="contractor_earnings",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Frozen contractor payout for this offer; zero commission.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="currency",
            field=models.CharField(default="AUD", max_length=3),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="distance_source",
            field=models.CharField(
                choices=[
                    ("ROUTE", "Route distance (directions provider)"),
                    ("HAVERSINE", "Straight-line distance (fallback)"),
                ],
                default="HAVERSINE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="eta_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="pricing_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="services_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Admin-only breakdown component.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Frozen final total for this offer; never recomputed.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="travel_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Admin-only breakdown component.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dispatchoffer",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED_PENDING_PAYMENT", "Accepted, awaiting payment"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="BookingQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_snapshot",
                    models.JSONField(
                        help_text="Frozen service selections, names and prices at quote time."
                    ),
                ),
                (
                    "services_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("maximum_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                ("pricing_version", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_quotes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking quote",
                "verbose_name_plural": "Booking quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.bookingquote",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingquote",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="bookings_bo_custome_95daf7_idx",
            ),
        ),
    ]
