# Generated by Django 5.2.17 on 2026-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_booking_currency_booking_max_total_and_more"),
        ("contractors", "0003_contractorcurrentlocation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dispatchoffer",
            name="unique_offer_per_booking_contractor",
        ),
        migrations.AddField(
            model_name="booking",
            name="dispatch_round",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Incremented on each retry; offers are scoped to a round.",
            ),
        ),
        migrations.AddField(
            model_name="dispatchoffer",
            name="dispatch_round",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="dispatchoffer",
            constraint=models.UniqueConstraint(
                fields=("booking", "contractor", "dispatch_round"),
                name="unique_offer_per_booking_contractor_round",
            ),
        ),
    ]
