# Generated by Django 5.2.17 on 2026-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0010_remove_dispatchoffer_unique_offer_per_booking_contractor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
