# Generated by Django 5.2.17 on 2026-09-27 09:54

from django.db import migrations, models
from django.db.models import F


def backfill_close_reason(apps, schema_editor):
    """
    العروض المغلقة قبل هذا الحقل.

    📌 الإلغاء يكتب responded_at للعروض = cancelled_at للحجز حرفيًا (نفس
       `now`)، فالتطابق يميّز "أُلغي الحجز" عن "انتهت المهلة" بلا تخمين.
    """
    DispatchOffer = apps.get_model("bookings", "DispatchOffer")
    DispatchOffer.objects.filter(status="DECLINED").update(close_reason="DECLINED")
    DispatchOffer.objects.filter(
        status="EXPIRED", booking__cancelled_at__isnull=False, responded_at=F("booking__cancelled_at")
    ).update(close_reason="BOOKING_CANCELLED")
    DispatchOffer.objects.filter(status="EXPIRED", close_reason="").update(close_reason="TIMED_OUT")


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_booking_cancellation_reason_booking_cancelled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchoffer",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DECLINED", "Declined by the contractor"),
                    ("TIMED_OUT", "Not answered in time"),
                    ("BOOKING_CANCELLED", "Booking cancelled"),
                ],
                default="",
                help_text="Why a DECLINED/EXPIRED offer was closed.",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_close_reason, migrations.RunPython.noop),
    ]
